### ISSUE TITLE
MSP drivers

### ISSUE THREAD

**Issue by sh4k4** [tegzwn/HiSTBLinuxKernel#1]
Can you upload msp drivers (common, msp folders with kernel and userspace drivers)? Thanks.

**Comment by tegzwn** [comment]
HiSTBLinuxV100R005C00SPC050:
https://drive.google.com/file/d/1rOL9ExmX3QBmJYY4qI0c7vu6nZ3E1LxA/view?usp=sharing
HiSTBLinuxV100R005C00SPC051_widevine:
https://drive.google.com/file/d/1CZ8Bxa10atnxdUBUwfg6AW1OauQz2dvx/view?usp=sharing

**Comment by 07bug** [comment]
https://github.com/zjkanjie/HiSTBLinuxV100R005C00SPC060
